use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# AppWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :app, AppWeb.Endpoint,
  http: [port: "${PORT}"],
  load_from_system_env: true,
  url: [host: "localhost", port: "${PORT}"],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: "${SECRET_KEY_BASE}",
  server: true,
  root: ".",
  version: Application.spec(:app, :vsn)

# Do not print debug messages in production
config :logger, level: :info

# Configures Repo
config :app, App.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "${RDS_USERNAME}",
  password: "${RDS_PASSWORD}",
  database: "${RDS_DB_NAME}",
  hostname: "${RDS_HOSTNAME}",
  pool_size: 25

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :app, AppWeb.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
